---
language: node_js
node_js:
  - "7.7.2"

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
    - bower_components

before_install:
  - npm config set spin false
  - npm install -g bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version

install:
  - yarn install --frozen-lockfile
  - bower install

script:
  - npm test
