dist: trusty
language: ruby
cache: bundler
node_js:
  - "7.7.2"
rvm:
  - 2.2.3

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
    - bower_components

before_install:
  - gem install bundler -v 1.12.5
  - cd frontend
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower
  - bower --version

before_script:
  - cd ..
  - psql -c 'create database hanuman_test;' -U postgres
  - bundle install && bundle exec rake db:migrate --trace
  - cd frontend
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

install:
  - yarn install --non-interactive
  - bower install
  - ./node_modules/testem/testem.js launchers

script:
  - yarn test
  - cd .. && bundle exec rspec


notifications:
  slack: suntoucher:VLwFnuhlLQDFquO2NnKZUvwV
  email: false
